//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolAccountManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public int ID { get; set; }
        public int IDNameProduction { get; set; }
        public int IDNamePartner { get; set; }
        public int CountProduction { get; set; }
        public System.DateTime DateOfSell { get; set; }
    
        public virtual NamePartner NamePartner { get; set; }
        public virtual NameProduction NameProduction { get; set; }
    }
}
