//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int ID { get; set; }
        public int IDTypePartner { get; set; }
        public int IDNamePartner { get; set; }
        public string DirectorLastName { get; set; }
        public string DirectorFirstName { get; set; }
        public string DirectorPatronymic { get; set; }
        public string EmailPartner { get; set; }
        public string Password { get; set; }
        public string PhonePartner { get; set; }
        public int MailIndex { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual NamePartner NamePartner { get; set; }
        public virtual TypePartner TypePartner { get; set; }
    }
}
