//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public int IDProductType { get; set; }
        public string NameProduction { get; set; }
        public int Article { get; set; }
        public decimal MinCostForPartner { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
